# -*- coding: utf-8 -*-
"""StoresClass.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fJAExTK8vxBTi929TmeqhfuEab8afYLa
"""

class Item:
  def __init__ (self, _name, _Target_price, _Aldi_price, _Walmart_price):
    self.name = _name
    self.Target_price = _Target_price
    self.Aldi_price = Aldi_price
    self.Walmart_price = Walmart_price

  def get_Target_price(self):
    return self.Target_price

  def get_Aldi_price(self):
    return self.Aldi_price

  def get_Walmart_price(self):
    return self.Walmart_price
   
  def add_to_cart_by_store(self):
	  
t
	  



  def __str__():
    msg = f"Sucessfully added {self.name} to the cart"
    return msg

