# -*- coding: utf-8 -*-
"""StoresClass.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fJAExTK8vxBTi929TmeqhfuEab8afYLa
"""

class Stores:
  def __init__ (self, item, Target, Aldi, Walmart):
    self.item = item
    self.Target = Target
    self.Aldi = Aldi
    self.Walmart = Walmart

  def get_Target(self):
    return self.Target

  def get_Aldi(self):
    return self.Aldi

  def get_Walmart(self):
    return self.Walmart

  def get_price(self):
    return self.price

  def set_Target(self, new_Target):
    self.Target = new_Target

  def set_Aldi(self, new_Aldi):
    self.Aldi = new_Aldi

  def set_Walmart(self, new_Walmart):
    self.Walmart = new_Walmart

  def set_item(self, new_item):
    self.item = new_item

  def __str__():
    msg = f"Sucessfully added {self.item} to the cart"
    return msg

